---
apiVersion: v1
kind: ReplicationController
metadata:
  name: openvpn-authd
  namespace: openvpn
  labels:
    name: openvpn-authd
spec:
  replicas: 2
  selector:
    name: openvpn-authd
  template:
    metadata:
      labels:
        name: openvpn-authd
    spec:
      containers:
      - name: vault-sidekick
        image: quay.io/ukhomeofficedigital/vault-sidekick:v0.0.3
        args:
          - -logtostderr=true
          - -v=3
          - -tls-skip-verify=true
          - -auth=/etc/vault/vault.yml
          - -cn=secret:platform/platform_tls:fmt=cert,file=platform_tls
        env:
          - name: VAULT_ADDR
            value: https://vault.platform.cluster.local:8200
        volumeMounts:
        - name: secrets
          mountPath: /etc/secrets
        - name: vault
          mountPath: /etc/vault
      - name: oauth-proxy
        image: gambol99/oauth-proxy:0.0.1
        args:
          - -logtostderr=true
          - -v=10
          - -interface=:443
          - -tls-cert=/etc/secrets/platform_tls.crt
          - -tls-private-cert=/etc/secrets/platform_tls.key
          - -clientid=openvpn
          - -client-secret=**OAUTH_CLIENT_SECRET**
          - -redirect-url=https://**EXTERNAL_DNS_NAME_FOR_KUBEACCESS**/oauth/callback
          - -discovery-url=https://**EXTERNAL_OAUTH_DISCOVERY_URL**/auth/realms/commons
          - -upstream=http://127.0.0.1:8082
          - -accepted-domains=*
          - -scopes=vpn-user
          - -requires-roles=openvpn:vpn-user
          - -session-limit=2m
        ports:
        - containerPort: 443
        volumeMounts:
        - name: secrets
          mountPath: /etc/secrets
      - name: openvpn-authd
        image: quay.io/ukhomeofficedigital/openvpn-authd
        imagePullPolicy: Always
        args:
          - -logtostderr=true
          - -v=10
          - -port=8082
          - -openvpn-servers=**LIST_OF_OPENVPN_ELB**
          - -vault-pki-path=openvpn-authd/issue/openvpn
          - -vault-password=**VAULT_PASSWORD**
          - -vault-username=openvpn-authd
          - -openvpn-servers=**COMMA_SEPARATED_LIST_OF_OPENVPN_ELBS**
          - -session=3h
        env:
          - name: VAULT_ADDR
            value: https://vault.platform.cluster.local:8200
      volumes:
      - name: vault
        secret:
          secretName: vault
      - name: secrets
        source:
          emptyDir: {}
