apiVersion: v1
kind: ReplicationController
metadata:
  name: brp-redis
spec:
  replicas: 1
  selector:
    name: brp-redis
  template:
    metadata:
      labels:
        name: brp-redis
    spec:
      containers:
      - name: redis
        image: vaijab/redis:latest
        ports:
        - containerPort: 6379
        command:
          - "/run.sh"
        resources:
          limits:
            cpu: "0.1"
        volumeMounts:
        - mountPath: /var/lib/redis
          name: data
      volumes:
        - name: data
          emptyDir: {}
