---
apiVersion: v1
kind: Secret
metadata:
  name: skydns-secrets
data:
  kubeconfig: |
    # below needs to be base64 encoded
    apiVersion: v1
    kind: Config
    preferences: {}
    clusters:
      - cluster:
          insecure-skip-tls-verify: true
          server: https://10.200.0.1:443
        name: default
    contexts:
    - context:
        cluster: default
        user: skydns
      name: default
    current-context: default
    users:
    - name: skydns
      user:
        token: <SKYDNS USER TOKEN>
