---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: vault-proxy
  name: vault-proxy
  namespace: platform
spec:
  type: NodePort
  ports:
    - name: https
      port: 443
      targetPort: 443
      nodePort: 32701
  selector:
    name: vault-proxy
