---
kind: Service
apiVersion: v1
metadata:
  namespace: platform
  name: vault
  labels:
    name: vault
spec:
  clusterIP: 10.200.10.11
  ports:
  - protocol: TCP
    port: 8200
    targetPort: 8200
