---
AWSTemplateFormatVersion: '2010-09-09'
Description: CoreOS etcd Cluster Volumes Stack in {{ env }} environment
Resources:
{%- for node in etcd_nodes %}
  EtcdNode{{ loop.index0 }}Volume:
    Type: AWS::EC2::Volume
    Properties:
      Size: 10
      VolumeType: gp2
      AvailabilityZone:
        Fn::Select:
        - {{ node['az_id'] }}
        - Fn::GetAZs: ''
      Tags:
        - Key: Name
          Value: {{ env }}-etcd-node{{ loop.index0 }}-volume
        - Key: Env
          Value: {{ env }}

{%- endfor %}

Outputs:
{%- for node in etcd_nodes %}
  EtcdNode{{ loop.index0 }}Volume:
    Value: {Ref: EtcdNode{{ loop.index0 }}Volume}
{%- endfor %}
