---
AWSTemplateFormatVersion: '2010-09-09'
Description: Kubernetes API Internal ELB
Outputs:
  ELBSG:
    Value: {Ref: ELBSG}
  ELB:
    Value: {Ref: ELB}
Resources:
  ELBSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Kubernetes API Internal ELB SG
      VpcId: {{ get_vpc_id(vpc_conn, vpc_name) }}
      SecurityGroupIngress:
        - IpProtocol: tcp
          CidrIp: 0.0.0.0/0
          FromPort: 6443
          ToPort: 6443
      SecurityGroupEgress:
        - IpProtocol: tcp
          FromPort: 6443
          ToPort: 6443
          DestinationSecurityGroupId: {{ get_stack_output(cf_conn, infra_stack_name, 'SecureDefaultSG') }}

  DefaultSGIngress:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      GroupId: {{ get_stack_output(cf_conn, infra_stack_name, 'SecureDefaultSG') }}
      IpProtocol: tcp
      SourceSecurityGroupId: {Ref: ELBSG}
      FromPort: 6443
      ToPort: 6443

  ELB:
    Type: AWS::ElasticLoadBalancing::LoadBalancer
    Properties:
      CrossZone: true
      Scheme: Internal
      Subnets:
        - {{ get_stack_output(cf_conn, infra_stack_name, 'SecureSubnet0') }}
        - {{ get_stack_output(cf_conn, infra_stack_name, 'SecureSubnet1') }}
        - {{ get_stack_output(cf_conn, infra_stack_name, 'SecureSubnet2') }}
      SecurityGroups:
        - {Ref: ELBSG}
      HealthCheck:
        Target: 'TCP:6443'
        HealthyThreshold: 2
        Interval: 30
        Timeout: 5
        UnhealthyThreshold: 2
      ConnectionDrainingPolicy:
        Enabled: true
        Timeout: 30
      Listeners:
      - LoadBalancerPort: 6443
        Protocol: TCP
        InstancePort: 6443
        InstanceProtocol: TCP
      Tags:
      - Key: Name
        Value: {{ dev }}-kubernetes-elb
      - Key: Env
        Value: {{ env }}
      - Key: Service
        Value: vault
      - Key: Scheme
        Value: internal

  ELBDNS:
    Type: AWS::Route53::RecordSetGroup
    Properties:
      HostedZoneName: {{ dns_zone_name }}.
      RecordSets:
        - Name: kubeapi{% if env != 'prod' %}-{{ env }}{% endif %}.{{ dns_zone_name }}
          Type: A
          AliasTarget:
            HostedZoneId:
              'Fn::GetAtt':
                - ELB
                - CanonicalHostedZoneNameID
            DNSName:
              'Fn::GetAtt':
                - ELB
                - DNSName
