---
apiVersion: v1
kind: Service
metadata:
  name: keycloak
  namespace: platform
  labels:
    name: keycloak
spec:
  type: NodePort
  ports:
    - name: http
      port: 80
      targetPort: 8080
      nodePort: 32702
    - name: https
      port: 443
      targetPort: 443
      nodePort: 32703
  selector:
    name: keycloak
